### ISSUE TITLE
Add support for a disabled mods folder

### ISSUE THREAD

**Issue by UlmStephen** [Slaynash/VRCModUpdater#10]
Sometimes mods are so broken you need to remove them, but still would want them to be auto updated when fixed. Adding support for a disabled mods folder would resolve this conflict.

**Comment by rakosi2** [comment]
This has been added and now can be closed. 
You can put them in the folder `VRChat\Mods\Broken` and will automatically be moved to Mods and updated when the mod gets fixed/updated.
