### ISSUE TITLE
[Bug] mods in a zip folder are skipped

### ISSUE THREAD

**Issue by rakosi2** [Slaynash/VRCModUpdater#3]
The only mod to do this is VRCEyeTracking as zip files are not allowed except in special cases where it is grandfathered in.  Rule 2 of mod Technical guidelines.

**Comment by Anonymous-BCFED** [comment]
UnityExplorer is also distributed as a ZIP file, for some reason.  It's not in the repo, though.

**Comment by Slaynash** [comment]
VREyeTracking is provided as a DLL, and UnityExplorer isn't part of the VRCMG mod API

**Comment by rakosi2** [comment]
This ticket was opened before VREyeTracking was just a single dll file. Feel free to close it.
