### ISSUE TITLE
Object Reference not set to an Instance of an Object at VRCModUpdater.Core.UpdaterWindow.CheckLightTheme()

### ISSUE THREAD

**Issue by H4x0r-000** [Slaynash/VRCModUpdater#9]
I not completely sure why it throws this error, but I downloaded the source and temporarily disabled CheckLightTheme() and the Download functionality for the Core Dll, because my change of CheckLightTheme() would be overwriten. Maybe because I use windows 7 still. Please make it more win7 freindly.

Here is a screenshot of the error message:
![image](https://user-images.githubusercontent.com/76412429/122937435-46a6c880-d372-11eb-89fc-3608f10e6ec2.png)

**Comment by untuned** [comment]
Windows 7 is an end of life system, your best bet is to update it.
